"""empty message

Revision ID: 2b372727c7ad
Revises: 
Create Date: 2026-03-20 20:15:44.154595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b372727c7ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accesorios_name', sa.String(length=50), nullable=False),
    sa.Column('tipo_de_accesorios', postgresql.ENUM('cabeza', 'gafas', 'color', name='accessories_type'), nullable=False),
    sa.Column('precio_pescado', sa.Integer(), nullable=False),
    sa.Column('path_accesorio', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('michi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('michi_name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('michi_name')
    )
    op.create_table('michi_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('michi_id', sa.Integer(), nullable=False),
    sa.Column('accesorios_id', sa.Integer(), nullable=True),
    sa.Column('esta_equipado', sa.Boolean(), nullable=False),
    sa.Column('pescados_totales', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accesorios_id'], ['accesorios.id'], ),
    sa.ForeignKeyConstraint(['michi_id'], ['michi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('michi_id')
    )
    op.create_table('partida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('michi_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('accesorio', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['michi_id'], ['michi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partida')
    op.drop_table('michi_inventario')
    op.drop_table('michi')
    op.drop_table('user')
    op.drop_table('accesorios')
    # ### end Alembic commands ###
